In this notebook, we are going to make two dataframes for verdant power's ADCP data using Pandas. These dataframes include:
* Depth dependent data
* Depth averaged data

In [4]:
import pandas as pd
import numpy as np

First we load each sheet of data for the station that we want as dataframe, then clean the data and come up with the depth-averaged data as time-series, then merge them together.

In [7]:
df1 = pd.read_excel('./14 updated sites/ADCP-Data_Deployment-Period1.xlsx', sheet_name='Station B',skiprows=17)
df2 = pd.read_excel('./14 updated sites/ADCP-Data_Deployment-Period2.xlsx', sheet_name='Station B-2',skiprows=17)

## Apply Orientation Corrections

Before merging, we apply orientation corrections to the direction column (column 7: 'Dir') based on analysis from orientation-correction.ipynb:
- **Deployment Period 1**: Dir_corrected = Dir + (-5.53)°
- **Deployment Period 2**: Dir_corrected = Dir + (3.2)°

In [8]:
# Apply orientation correction to Deployment Period 1
# Dir_corrected = Dir + (-5.53)°
correction_p1 = -5.53
if 'Dir' in df1.columns:
    df1['Dir'] = pd.to_numeric(df1['Dir'], errors='coerce') + correction_p1
    print(f"Deployment Period 1: Applied correction of {correction_p1}° to 'Dir' column")
else:
    print("Warning: 'Dir' column not found in df1")
    print(f"Available columns: {list(df1.columns)}")

Deployment Period 1: Applied correction of -5.53° to 'Dir' column

In [9]:
# Apply orientation correction to Deployment Period 2
# Dir_corrected = Dir + (3.2)°
correction_p2 = 3.20
if 'Dir' in df2.columns:
    df2['Dir'] = pd.to_numeric(df2['Dir'], errors='coerce') + correction_p2
    print(f"Deployment Period 2: Applied correction of {correction_p2}° to 'Dir' column")
else:
    print("Warning: 'Dir' column not found in df2")
    print(f"Available columns: {list(df2.columns)}")

Deployment Period 2: Applied correction of 3.2° to 'Dir' column

## Merge Corrected Dataframes
Now that orientation corrections have been applied to both deployment periods, we can merge them together.

In [10]:
df = pd.concat([df1, df2], ignore_index=True)
df.head()

,Date & Time,Date & Time.1,Date & Time.2,Unnamed: 3,Eas,Nor,Mag,Dir,Unnamed: 8,Eas.1,...,Mag.47,Dir.47,Eas.48,Nor.48,Mag.48,Dir.48,Eas.49,Nor.49,Mag.49,Dir.49
0,(UTC),(EDT),(EST),NaN,(mm/s),(mm/s),(mm/s),NaN,NaN,(mm/s),...,(mm/s),(deg T),(mm/s),(mm/s),(mm/s),(deg T),(mm/s),(mm/s),(mm/s),(deg T)
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-23 14:00:00,2024-10-23 10:00:00,2024-10-23 09:00:00,NaN,185,69,197,64.47,NaN,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-10-23 14:10:00,2024-10-23 10:10:00,2024-10-23 09:10:00,NaN,91,46,102,57.47,NaN,-88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-10-23 14:20:00,2024-10-23 10:20:00,2024-10-23 09:20:00,NaN,13,34,36,14.47,NaN,-181,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
columns_to_drop = [c for c in ['Date & Time', 'Date & Time.1', 'Unnamed: 3'] if c in df.columns]
df.drop(columns=columns_to_drop, inplace=True)

In [12]:
if 'Unnamed: 8' in df.columns:
    unnamed_8_index = df.columns.get_loc('Unnamed: 8')
    columns_to_drop = df.columns[unnamed_8_index:]
    df.drop(columns=columns_to_drop, inplace=True)

In [13]:
df = df.drop(index=[0, 1])
df.head()

         Date & Time.2   Eas Nor  Mag     Dir
2  2024-10-23 09:00:00   185  69  197   64.47
3  2024-10-23 09:10:00    91  46  102   57.47
4  2024-10-23 09:20:00    13  34   36   14.47
5  2024-10-23 09:30:00   -79   9   80  271.47
6  2024-10-23 09:40:00  -175  -1  175  264.47

In [14]:
df.to_csv('depthAvg_ADCPdata.csv', index=False)

df is out data frame for depth-averaged ADCP data for station B.

In [15]:
df.count()

Date & Time.2    16543
Eas              16543
Nor              16543
Mag              16543
Dir              16542
dtype: int64

### Depth dependent data:

In [17]:
tidal_df1 = pd.read_excel('./14 updated sites/ADCP-Data_Deployment-Period1.xlsx', sheet_name='Station B',skiprows=13)
tidal_df2 = pd.read_excel('./14 updated sites/ADCP-Data_Deployment-Period2.xlsx', sheet_name='Station B-2',skiprows=13)

In [18]:
# Check what columns are in the depth-dependent dataframes
print("tidal_df1 columns:")
print(list(tidal_df1.columns))
print(f"\nTotal columns: {len(tidal_df1.columns)}")

tidal_df1 columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Bin #:', 1, '1.1', '1.2', '1.3', 2, '2.1', '2.2', '2.3', 3, '3.1', '3.2', '3.3', 4, '4.1', '4.2', '4.3', 5, '5.1', '5.2', '5.3', 6, '6.1', '6.2', '6.3', 7, '7.1', '7.2', '7.3', 8, '8.1', '8.2', '8.3', 9, '9.1', '9.2', '9.3', 10, '10.1', '10.2', '10.3', 11, '11.1', '11.2', '11.3', 12, '12.1', '12.2', '12.3', 13, '13.1', '13.2', '13.3', 14, '14.1', '14.2', '14.3', 15, '15.1', '15.2', '15.3', 16, '16.1', '16.2', '16.3', 17, '17.1', '17.2', '17.3', 18, '18.1', '18.2', '18.3', 19, '19.1', '19.2', '19.3', 20, '20.1', '20.2', '20.3', 21, '21.1', '21.2', '21.3', 22, '22.1', '22.2', '22.3', 23, '23.1', '23.2', '23.3', 24, '24.1', '24.2', '24.3', 25, '25.1', '25.2', '25.3', 26, '26.1', '26.2', '26.3', 27, '27.1', '27.2', '27.3', 28, '28.1', '28.2', '28.3', 29, '29.1', '29.2', '29.3', 30, '30.1', '30.2', '30.3', 31, '31.1', '31.2', '31.3', 32, '32.1', '32.2', '32.3', 33, '33.1', '33.2', '33.3', 34, '34.1', '34.2', '34.3', 35, '35.1', '35.2', '35.3', 36, '36.1', '36.2', '36.3', 37, '37.1', '37.2', '37.3', 38, '38.1', '38.2', '38.3', 39, '39.1', '39.2', '39.3', 40, '40.1', '40.2', '40.3', 41, '41.1', '41.2', '41.3', 42, '42.1', '42.2', '42.3', 43, '43.1', '43.2', '43.3', 44, '44.1', '44.2', '44.3', 45, '45.1', '45.2', '45.3', 46, '46.1', '46.2', '46.3', 47, '47.1', '47.2', '47.3', 48, '48.1', '48.2', '48.3', 49, '49.1', '49.2', '49.3']

Total columns: 205

## Apply Orientation Corrections to Depth-Dependent Data
Apply the same orientation corrections to all direction columns in the depth-dependent dataframes:
- **Deployment Period 1**: All Dir columns + (-5.53)°
- **Deployment Period 2**: All Dir columns + (3.2)°

In [19]:
# Apply orientation correction to Deployment Period 1 depth-dependent data
# Dir columns are: 'Unnamed: 7' (depth-averaged) + columns ending in '.3' (depth bins)
correction_p1 = -5.53

# Find all direction columns: 'Unnamed: 7' and columns ending with '.3'
dir_cols_p1 = [col for col in tidal_df1.columns if isinstance(col, str) and col.endswith('.3')]

print(f"Deployment Period 1 - Found {len(dir_cols_p1)} direction columns")
print(f"Direction columns: {dir_cols_p1[:5]}...")  # Show first 5

# Apply correction to all direction columns
for col in dir_cols_p1:
    tidal_df1[col] = pd.to_numeric(tidal_df1[col], errors='coerce') + correction_p1

print(f"Applied correction of {correction_p1}° to all direction columns in tidal_df1")

Deployment Period 1 - Found 49 direction columns
Direction columns: ['1.3', '2.3', '3.3', '4.3', '5.3']...
Applied correction of -5.53° to all direction columns in tidal_df1

In [20]:
# Apply orientation correction to Deployment Period 2 depth-dependent data
# Dir columns are: 'Unnamed: 7' (depth-averaged) + columns ending in '.3' (depth bins)
correction_p2 = 3.20

# Find all direction columns: 'Unnamed: 7' and columns ending with '.3'
dir_cols_p2 = [col for col in tidal_df2.columns if isinstance(col, str) and col.endswith('.3')]

print(f"Deployment Period 2 - Found {len(dir_cols_p2)} direction columns")
print(f"Direction columns: {dir_cols_p2[:5]}...")  # Show first 5

# Apply correction to all direction columns
for col in dir_cols_p2:
    tidal_df2[col] = pd.to_numeric(tidal_df2[col], errors='coerce') + correction_p2

print(f"Applied correction of {correction_p2}° to all direction columns in tidal_df2")

Deployment Period 2 - Found 49 direction columns
Direction columns: ['1.3', '2.3', '3.3', '4.3', '5.3']...
Applied correction of 3.2° to all direction columns in tidal_df2

In [21]:
tidal_df = pd.concat([tidal_df1, tidal_df2], ignore_index=True)
tidal_df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Bin #:,1,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Note, this time represents the beginning of ea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,Vertically Averaged Data,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date & Time,Date & Time,Date & Time,NaN,Eas,Nor,Mag,Dir,NaN,Eas,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
4,(UTC),(EDT),(EST),NaN,(mm/s),(mm/s),(mm/s),(deg T),NaN,(mm/s),...,(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-10-23 14:00:00,2024-10-23 10:00:00,2024-10-23 09:00:00,NaN,185,69,197,70,NaN,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-23 14:10:00,2024-10-23 10:10:00,2024-10-23 09:10:00,NaN,91,46,102,63,NaN,-88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-23 14:20:00,2024-10-23 10:20:00,2024-10-23 09:20:00,NaN,13,34,36,20,NaN,-181,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-23 14:30:00,2024-10-23 10:30:00,2024-10-23 09:30:00,NaN,-79,9,80,277,NaN,-243,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
if 'Unnamed: 2' in tidal_df.columns:
    distance_index = tidal_df.columns.get_loc('Unnamed: 2')
    columns_to_drop = tidal_df.columns[:distance_index]
    tidal_df.drop(columns=columns_to_drop, inplace=True)

In [23]:
if 'Unnamed: 2' in tidal_df.columns:
    distance_index = tidal_df.columns.get_loc('Unnamed: 2')
    columns_to_drop = tidal_df.columns[:distance_index]
    tidal_df.drop(columns=columns_to_drop, inplace=True)

In [24]:
tidal_df.head(10)

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Bin #:,1,1.1,1.2,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Vertically Averaged Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date & Time,NaN,Eas,Nor,Mag,Dir,NaN,Eas,Nor,Mag,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
4,(EST),NaN,(mm/s),(mm/s),(mm/s),(deg T),NaN,(mm/s),(mm/s),(mm/s),...,(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-10-23 09:00:00,NaN,185,69,197,70,NaN,11,-7,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-23 09:10:00,NaN,91,46,102,63,NaN,-88,-55,104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-23 09:20:00,NaN,13,34,36,20,NaN,-181,-67,193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-23 09:30:00,NaN,-79,9,80,277,NaN,-243,-61,251,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
if 'Unnamed: 3' in tidal_df.columns and 'Unnamed: 7' in tidal_df.columns:
    start_idx = tidal_df.columns.get_loc('Unnamed: 3')
    end_idx = tidal_df.columns.get_loc('Unnamed: 7')
    columns_to_drop = tidal_df.columns[start_idx:end_idx+1]
    print(f"Dropping columns: {columns_to_drop.tolist()}")
    tidal_df = tidal_df.drop(columns=columns_to_drop)
else:
    print("Columns 'Unnamed: 3' or 'Unnamed: 7' not found")
    print("Available columns:", tidal_df.columns.tolist())

Dropping columns: ['Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

In [26]:
if 'Unnamed: 0' in tidal_df.columns:
    distance_index = tidal_df.columns.get_loc('Unnamed: 0')
    columns_to_drop = tidal_df.columns[distance_index:]
    tidal_df.drop(columns=columns_to_drop, inplace=True)

In [27]:
tidal_df.head()

,Unnamed: 2,Bin #:,1,1.1,1.2,1.3,2,2.1,2.2,2.3,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date & Time,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
4,(EST),NaN,(mm/s),(mm/s),(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN,...,(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN

In [28]:
tidal_df.columns

Index(['Unnamed: 2',     'Bin #:',            1,        '1.1',        '1.2',
              '1.3',            2,        '2.1',        '2.2',        '2.3',
       ...
             '47.2',       '47.3',           48,       '48.1',       '48.2',
             '48.3',           49,       '49.1',       '49.2',       '49.3'],
      dtype='object', length=198)

In [29]:
tidal_df = tidal_df.drop(index=[0, 1, 2, 4, 5])
tidal_df.head()

,Unnamed: 2,Bin #:,1,1.1,1.2,1.3,2,2.1,2.2,2.3,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
3,Date & Time,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
6,2024-10-23 09:00:00,NaN,11,-7,13,117.47,12,-6,13,111.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-23 09:10:00,NaN,-88,-55,104,232.47,-82,-52,97,232.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-23 09:20:00,NaN,-181,-67,193,244.47,-171,-84,191,238.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-23 09:30:00,NaN,-243,-61,251,250.47,-246,-46,250,253.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
tidal_df.iloc[6067:6075]

,Unnamed: 2,Bin #:,1,1.1,1.2,1.3,2,2.1,2.2,2.3,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
6072,2024-12-04 12:00:00,NaN,-434,-31,435,260.47,-443,-64,448,256.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6076,Date & Time,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
6077,(EST),NaN,(mm/s),(mm/s),(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN,...,(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN,(mm/s),(mm/s),(mm/s),NaN
6078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6079,2024-12-04 13:25:00,NaN,172,99,198,63.20,180,125,219,58.20,...,141,48.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
tidal_df = tidal_df.drop(index=[6073, 6074, 6075, 6076, 6077, 6078])

In [32]:
tidal_df.iloc[6067:6075]

,Unnamed: 2,Bin #:,1,1.1,1.2,1.3,2,2.1,2.2,2.3,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
6072,2024-12-04 12:00:00,NaN,-434,-31,435,260.47,-443,-64,448,256.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6079,2024-12-04 13:25:00,NaN,172,99,198,63.20,180,125,219,58.20,...,141,48.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6080,2024-12-04 13:35:00,NaN,276,124,303,69.20,324,133,350,71.20,...,398,65.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6081,2024-12-04 13:45:00,NaN,354,136,379,72.20,358,120,378,75.20,...,599,68.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6082,2024-12-04 13:55:00,NaN,377,96,389,79.20,414,70,420,83.20,...,1041,72.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6083,2024-12-04 14:05:00,NaN,426,82,434,82.20,459,85,467,83.20,...,1126,72.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6084,2024-12-04 14:15:00,NaN,406,83,414,81.20,443,79,450,83.20,...,1202,70.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6085,2024-12-04 14:25:00,NaN,464,104,476,80.20,493,122,508,79.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
tidal_df.rename(columns={'Unnamed: 2': 'DateTime'}, inplace=True)
tidal_df.head()

,DateTime,Bin #:,1,1.1,1.2,1.3,2,2.1,2.2,2.3,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
3,Date & Time,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
6,2024-10-23 09:00:00,NaN,11,-7,13,117.47,12,-6,13,111.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-23 09:10:00,NaN,-88,-55,104,232.47,-82,-52,97,232.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-23 09:20:00,NaN,-181,-67,193,244.47,-171,-84,191,238.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-23 09:30:00,NaN,-243,-61,251,250.47,-246,-46,250,253.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
tidal_df['DateTime'] = pd.to_datetime(tidal_df['DateTime'], errors='coerce')

C:\Users\Hosse\AppData\Local\Temp\ipykernel_21088\1731070863.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  tidal_df['DateTime'] = pd.to_datetime(tidal_df['DateTime'], errors='coerce')

In [35]:
tidal_df.head()

,DateTime,Bin #:,1,1.1,1.2,1.3,2,2.1,2.2,2.3,...,47.2,47.3,48,48.1,48.2,48.3,49,49.1,49.2,49.3
3,NaT,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN,...,Mag,NaN,Eas,Nor,Mag,NaN,Eas,Nor,Mag,NaN
6,2024-10-23 09:00:00,NaN,11,-7,13,117.47,12,-6,13,111.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-10-23 09:10:00,NaN,-88,-55,104,232.47,-82,-52,97,232.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-10-23 09:20:00,NaN,-181,-67,193,244.47,-171,-84,191,238.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-10-23 09:30:00,NaN,-243,-61,251,250.47,-246,-46,250,253.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
tidal_df.to_csv('depthDep_ADCPdata.csv', index=False)